### ISSUE TITLE
Integral v6 is a Trojan:Win32/Wacatac.B!ml(Windows Security)

### ISSUE THREAD

**Issue by toni-chess** [aronpetko/integral#149]
Hi again!

integral_avx2.exe --------- | Trojan:Win32/Wacatac.B!ml
integral_avx2_bmi2.exe --- | Trojan:Win32/Wacatac.B!ml
integral_avx512.exe ------- | OK
integral_sse41_popcnt.exe | OK

![Integral v6 BMI2](https://github.com/user-attachments/assets/7ca8de5d-a2c9-46ea-9756-0301f82393f7)

Windows Security also saw Integral v5 as a virus, but after a few days it(Integral v5) was normal for it.
Note I have Kaspersky Total Security, but I can't scan these files because of Windows Security block downloads.
Best Regards!

**Comment by aronpetko** [comment]
Unfortunately, I'm not sure I can really do anything about it. I could try signing the Integral binaries with a certificate, but I'd much rather users just compile Integral directly from the source code if you feel endangered by the false trojan warning.

Alternatively, you can exempt Integral from your Windows Defender if you can't use it because it gets blocked.
